name: "ATIV Solana Anchor Build"
author: "ATIV sosin"
description: "Build a Solana program with Anchor"
branding:
  icon: anchor
  color: red
inputs:
  args:
    description: "anchor build arguments"
    required: false
    default: ""
runs:
  using: "docker"
  image: "docker://sosin/ativ-solana-dev:0.24.2"
  entrypoint: shell-exec
  args:
    - "anchor build ${{ inputs.args }}"
