name: 'Solana Anchor Build'
author: 'MRGN Labs'
description: 'Run an anchor build command'
branding:
  icon: anchor
  color: red
inputs:
  args:
    description: 'anchor build arguments'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://mrgnlabs/solana-dev:0.0.2-alpha'
  entrypoint: shell-exec
  args: 
    - 'anchor build ${{ inputs.args }}'
